### ISSUE TITLE
Print a warning when running `skunk` without a `coverage/.resultset.json` 

### ISSUE THREAD

**Issue by etagwerker** [fastruby/skunk#25]
In the README.md: 

> To get the best results, make sure that you have `coverage/.resultset.json` in
your application directory. That way `skunk` knows what's the status of your
test suite + code coverage.

Running `skunk` without that file is kind of pointless. The whole idea of the "StinkScore" is to combine RubyCritic's cost with SimpleCov's lack of coverage, in order to get a realistic "StinkScore"

So we should make sure the user understands that the scores that they're getting is not that useful.

**Comment by bronzdoc** [comment]
If the result without `coverage/.resultset.json` is not useful then we should make it a requirement to run `skunk`

**Comment by bronzdoc** [comment]
ping @etagwerker

**Comment by etagwerker** [comment]
@bronzdoc I don't think we should make it a requirement, I think it should output a noticeable warning. We have to assume that sometimes a project has no test suite, so they won't have code coverage data, but as they add coverage to their codebase, they might want to see the evolution of their stink score average (related to #5)

**Comment by FionaDL** [comment]
@etagwerker @bronzdoc Maybe there should also be a note in the documentation about having to change the path within the file?

**Comment by etagwerker** [comment]
@FionaDL I think that is an issue in `SimpleCov`, not `skunk` -> https://github.com/colszowka/simplecov 

I think it would be useful if `SimpleCov` had a way to generate `coverage/.resultset.json` with relative paths, instead of absolute paths.
