### ISSUE TITLE
[0.4.2] undefined local variable or method `coverage` for RubyCritic::AnalysedModule

### ISSUE THREAD

**Issue by matiasgarcia** [fastruby/skunk#43]
Hi!

I wanted to try out `skunk` in my project and it's breaking.

Before running it, I ran my test suite with `simplecov` and I have the `coverage/.resultset.json` in my project folder.

When running `skunk`, I get this:

```
Traceback (most recent call last):
  15: from /home/matias/.rvm/gems/ruby-2.5.7@foo/bin/ruby_executable_hooks:24:in `<main>'
	14: from /home/matias/.rvm/gems/ruby-2.5.7@foo/bin/ruby_executable_hooks:24:in `eval'
	13: from /home/matias/.rvm/gems/ruby-2.5.7@foo/bin/skunk:23:in `<main>'
12: from /home/matias/.rvm/gems/ruby-2.5.7@foo/bin/skunk:23:in `load'
	11: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/exe/skunk:10:in `<top (required)>'
	10: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/application.rb:21:in `execute'
9: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/default.rb:25:in `execute'
	 8: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/default.rb:31:in `report'
	 7: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/rubycritic-4.1.0/lib/rubycritic/commands/status_reporter.rb:17:in `score='
6: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/rubycritic-4.1.0/lib/rubycritic/commands/status_reporter.rb:24:in `update_status'
	 5: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/status_reporter.rb:29:in `update_status_message'
	 4: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/status_reporter.rb:71:in `table_options'
3: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/status_reporter.rb:53:in `sorted_modules'
	 2: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/status_reporter.rb:53:in `sort_by'
	 1: from /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/cli/commands/status_reporter.rb:53:in `each'
/home/matias/.rvm/gems/ruby-2.5.7@foo/gems/skunk-0.4.2/lib/skunk/rubycritic/analysed_module.rb:34:in `stink_score': undefined local variable or method `coverage' for #<RubyCritic::AnalysedModule:0x00005635e358e9d0> (NameError)
```

This is the Gemfile.lock

```
    skunk (0.4.2)
      rubycritic (~> 4.0)
      terminal-table (~> 1.8.0)
    rubycritic (4.1.0)
      flay (~> 2.8)
      flog (~> 4.4)
      launchy (= 2.4.3)
      parser (~> 2.6.0)
      rainbow (~> 3.0)
      reek (~> 5.0, < 6.0)
      ruby_parser (~> 3.8)
      tty-which (~> 0.4.0)
      virtus (~> 1.0)
```

I realized that you are [monkey patching `RubyCritic::AnalysedModule`](https://github.com/fastruby/skunk/blob/master/lib/skunk/rubycritic/analysed_module.rb) and relying on the `coverage` method that, at least on [4.1.0](https://github.com/whitesmith/rubycritic/blob/v4.1.0/lib/rubycritic/core/analysed_module.rb) isn't available. 

-------------------

After some digging, I realized that you made a fix in the RubyCritic library for [4.2.0](https://github.com/whitesmith/rubycritic/blob/v4.2.0/lib/rubycritic/core/analysed_module.rb) so I guess the fix for this would be bumping the requirement to at least that version unless I am missing something.

When noticing that, I made a [fork](https://github.com/matiasgarcia/skunk/commit/50541432c602659a139aea15e70331c16693be22) to update the requirements and that's when I realized that I was forced to upgrade my project to simplecov 0.18, which seems to break the gem [according to this](https://github.com/fastruby/skunk/issues/40) so I am a bit lost figuring out the proper fix.

Thanks!

**Comment by matiasgarcia** [comment]
Sorry, I checked again and realized that I could force my project to use simplecov `0.17.x` so it seems to be working.

**Comment by etagwerker** [comment]
@matiasgarcia Thanks for submitting this issue! I believe #53 will add support for SimpleCov's latest version.
