### ISSUE TITLE
[BUG] Nested /test or /spec folders are not ignored

### ISSUE THREAD

**Issue by arielj** [fastruby/skunk#60]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and didn't find this feature
- [x] I checked to make sure that this feature has not already been requested

**Branch/Commit:**

Main branch.

**Describe the feature:**

> **As a User**
> **When I run skunk on a directory that has nested /spec or /test folders**
> **Then I don't see reports for files inside nested /spec or /test folders**

**Problem:**
Currenty, we are ignoring folders that starts with `test` or `spec` https://github.com/fastruby/skunk/blob/e038ce3c1712603334f72e65967faf3a43abe977/lib/skunk/cli/commands/status_reporter.rb#L46 but we are not ignoring folders that are nested like `engines/my_engine/spec/`.

This makes skunk to report those files as 0% test coverage and really high skunk scores.

**I will abide by the [code of conduct](https://github.com/fastruby/skunk/blob/main/CODE_OF_CONDUCT.md)**

**Comment by etagwerker** [comment]
@bronzdoc @bronzdoc Can this be closed? I assume that when @rdormer merged #65 it solved this bug?
