### ISSUE TITLE
[REQUEST] Ruby versions compatibility

### ISSUE THREAD

**Issue by arielj** [fastruby/skunk#67]
**Describe the feature:**

> **As a User**
> **I want to see which version of Skunk I can use for my Ruby version**

**Problem:**

The Ruby version requirement for Skunk at ruby gems is not accurate for older versions at least.

https://rubygems.org/gems/skunk/versions/0.4.2 says Ruby >= 0, but that version depends on reek 5.4.0 which depends on Ruby >= 2.3.0.

Maybe a table of which version of skunk is recommended for each version of ruby is useful.

**I will abide by the [code of conduct](https://github.com/fastruby/skunk/blob/main/CODE_OF_CONDUCT.md)**

**Comment by etagwerker** [comment]
@arielj I think that is a great idea. I'm not sure why Rubygems says that skunk is compatible with Ruby >= 0, the gemspec is pretty clear here: https://github.com/fastruby/skunk/blob/main/skunk.gemspec#L17 

Any ideas why Rubygems is misreporting that information, @bronzdoc?

**Comment by bronzdoc** [comment]
@etagwerker weird  idk, I opened an issue https://github.com/rubygems/rubygems.org/issues/2651

**Comment by sonalkr132** [comment]
> https://rubygems.org/gems/skunk/versions/0.4.2 says Ruby >= 0

The link is for 0.4.2. ruby requirement was added in 0.5.0 https://github.com/fastruby/skunk/commit/cdfc9ff6d1649cbbf0752cb134816ec4ad02b16e

**Comment by etagwerker** [comment]
@sonalkr132 Thanks for looking into this! 🤦‍♂️

**Comment by bronzdoc** [comment]
Closing since this is not an issue, we just need to push the latest version to rubygems that contains the ruby requirement
